# Generated by Django 6.0.2 on 2026-03-03 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildAgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageLimit', models.IntegerField()),
            ],
            options={
                'db_table': 'child_age_limit',
            },
        ),
        migrations.CreateModel(
            name='SocietySettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('deliveryAllowed', models.BooleanField(default=True)),
                ('visitorAllowed', models.BooleanField(default=True)),
                ('defaultAgeLimit', models.IntegerField(default=3)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'society_settings',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childName', models.CharField(max_length=30)),
                ('childAge', models.IntegerField()),
                ('childPhoto', models.FileField(blank=True, null=True, upload_to='child_photos/')),
                ('inTime', models.TimeField(blank=True, null=True)),
                ('outTime', models.TimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'child',
                'ordering': ['childName'],
            },
        ),
        migrations.CreateModel(
            name='ChildEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitDateTime', models.DateTimeField(blank=True, null=True)),
                ('childId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_logs', to='society.child')),
                ('markedBy', models.ForeignKey(blank=True, help_text='Usually security user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_entries_marked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'child_entry_log',
                'ordering': ['-entryDateTime'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryPerson', models.CharField(max_length=30)),
                ('deliveryAllowed', models.BooleanField(default=True)),
                ('deliveryStatus', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected')], default='PENDING', max_length=10)),
                ('storedAtSecurity', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('collectedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_collected', to=settings.AUTH_USER_MODEL)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('receivedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('collectedTime', models.DateTimeField(blank=True, null=True)),
                ('deliveryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='society.delivery')),
            ],
            options={
                'db_table': 'delivery_log',
                'ordering': ['-receivedTime'],
            },
        ),
        migrations.CreateModel(
            name='SocietyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=100)),
                ('noticeDescription', models.TextField()),
                ('postedDate', models.DateField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'society_notice',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(max_length=30)),
                ('staffRole', models.CharField(choices=[('SECURITY', 'Security'), ('HELPER', 'House Helper')], max_length=20)),
                ('attendanceDate', models.DateField(default=django.utils.timezone.now)),
                ('staffInTime', models.TimeField()),
                ('staffOutTime', models.TimeField()),
                ('markedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendance_marked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_attendance',
                'ordering': ['-attendanceDate'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorName', models.CharField(max_length=30)),
                ('visitorType', models.CharField(choices=[('GUEST', 'Guest'), ('SERVICE', 'Service Provider')], max_length=15)),
                ('visitPurpose', models.CharField(blank=True, max_length=100, null=True)),
                ('priorPermission', models.BooleanField(default=False)),
                ('approvalStatus', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('approvedBy', models.ForeignKey(blank=True, help_text='Member/chairman who approved/rejected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to=settings.AUTH_USER_MODEL)),
                ('requestedBy', models.ForeignKey(blank=True, help_text='Usually security user who created the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitor',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='VisitorEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitTime', models.DateTimeField(blank=True, null=True)),
                ('markedEntryBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_marked', to=settings.AUTH_USER_MODEL)),
                ('markedExitBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_exits_marked', to=settings.AUTH_USER_MODEL)),
                ('visitorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_logs', to='society.visitor')),
            ],
            options={
                'db_table': 'visitor_entry_log',
                'ordering': ['-entryTime'],
            },
        ),
    ]
