# Generated by Django 6.0.2 on 2026-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('visitors_today', models.IntegerField(default=0)),
                ('deliveries_today', models.IntegerField(default=0)),
                ('insight_message', models.TextField()),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
